version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  devops-app:
    image: yosrijedidi/devops_project:1.0
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod

networks:
  mynetwork:
