version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  DevOps_Project:
    depends_on:
      - mysqldb
    image: fatma721/devops_project
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true

volumes:
  db: