version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devOps1
    volumes:
      - db:/var/lib/mysql
  backend:
    image: fatma721/devops_project:latest
    ports:
      - 8082:8082
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/devOps1?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.jpa.show-sql" : true,
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null  
      }'
    stdin_open: true
    tty: true

volumes:
  db: