version: "2.2"

services:
  db:
    image: "mysql:5.6"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password_here"
      MYSQL_DATABASE: "devops1"
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops1?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  db:
  mysql-data: