version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devops-projet
    volumes:
      - db:/var/lib/mysql
    networks:
          - common-net


  backendserver:
    image: fatma721/devops_project
    ports:
      - 8082:8082
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/devops-projet?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.jpa.show-sql" : true,
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null  
      }'
    stdin_open: true
    tty: true
    networks:
      - common-net

  nexus:
     image: sonatype/nexus3:latest
     ports:
     - "8081:8081"
     volumes:
       - nexus_data:/nexus-data
     environment:
            - NEXUS_CONTEXT=/
     networks:
        - common-net



volumes:
  db: