version: "2.22.0"
services:

  #cmd: docker-compose up

    db:
      image: "mysql:5.6"
      restart: unless-stopped
      environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=timesheet_db
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
    app-timesheet:
      depends_on:
        - mysqldb
      image: nourbenmehrez/timesheet-devops:1.1.0
      restart: on-failure
      ports:
        - 8082:8082
      #environment:


#  app:
#    build: app
#    restart: always

#  web:
#    build: web
#    restart: always
#    ports:
#      - 8080:8080
