version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devops-projet
    volumes:
      - db:/var/lib/mysql
    networks:
          - common-net


  backendserver:
    image: fatma721/devops_project
    ports:
      - 8082:8082
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/devops-projet?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.jpa.show-sql" : true,
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null  
      }'
    stdin_open: true
    tty: true
    networks:
      - common-net

  nexus:
     image: sonatype/nexus3
     ports:
     - "8081:8081"
     volumes:
       - nexus_data:/nexus-data
     environment:
            - NEXUS_CONTEXT=/
     networks:
        - common-net


  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - common-net

  grafana:
      image: grafana/grafana
      volumes:
        - grafana_data:/var/lib/grafana
        - grafana_config:/etc/grafana
        - grafana_plugins:/var/lib/grafana/plugins
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      networks:
        - common-net



volumes:
  db:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  prometheus_config:
  prometheus_data:
  grafana_data:
  grafana_config:
  grafana_plugins:

networks:
  common-net:
     driver: bridge
  sonarnet:
      driver: bridge