version: "2.22.0"
services:

  #cmd: docker-compose up
    db:
      image: "mysql:5.6"
      restart: unless-stopped
      environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=devops1
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql

environment:
        app:
        build:
        context: .
        dockerfile: dockerfile
        ports:
          - "8089:8089"
        depends_on:
          - mysql
        environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops1?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:

        volumes:
        mysql-data:


#  web:
#    build: web
#    restart: always
#    ports:
#      - 8080:8080
