pipeline {
    agent any
   
    stages {
        stage("Git Clone") {
            steps {
                script {
                    git branch: 'GestionInvoice',
                        url: 'https://github.com/NajlaNsiri/DEVOPS1.git'
                }
            }
        }

       stage('Nettoyage du projet') {
    steps {
        script {
            dir('DEVOPS1/DevOps_Project') {
                echo "Current directory: ${pwd()}"
                sh 'ls -la'  // List files in the directory
                sh 'mvn clean'
            }
        }
    }
}
    }
    
}
