pipeline {
    agent any
    stages {
        
        stage('clean Maven') {
            steps{
                script{
                    dir('DevOps_Project')
                    {sh "mvn clean" } 
                }
            }
        }
        
         stage('Compile') {
            steps {
                script {
                    dir('DevOps_Project')
                    {sh 'mvn compile'}
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    dir('DevOps_Project') 
                    { sh 'mvn test' }
                }
            }
        }
        
          stage('Build') {
              steps {
                 script {
                    dir('DevOps_Project')
                    {sh 'mvn package '}
                }
            }
        }
        
         stage("Docker build") {
            steps {
                script {
                    dir('DevOps_Project')
                    {sh 'docker build -t fatma721/devops_project .'}
                }
            }
        }
            stage("Docker Login") {
             steps {
                    script {
                     withCredentials([usernamePassword(credentialsId: 'DOCKER', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) 
                   {sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD" }
                }
            }
        }

        stage('SONARQUBE') {
            steps {
                script {
                    dir('DevOps_Project')
                    {sh 'mvn sonar:sonar -Dsonar.login=a82dd8f11a0e05755efc85425d6df78bc31346b290320bfa0341bd10d7e75ca6'}
                }
            }
        }
                
}
}
