version: "2.2"

services:
  db:
    image: "mysql:5.6"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: "devops1"
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  
volumes:
 
  mysql-data: